apiVersion: v1
kind: Service
metadata:
  name: devops-webpage-service
  labels:
    name: devops-webpage-service
    app: devops-webpage-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: devops-webpage-pod
    app: devops-webpage-app