apiVersion: v1
kind: Service
metadata:
  name: mean-app-angular-service
  labels:
    name: mean-app-angular-service
    app: mean-app-webpage
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: mean-app-angular-pod
    app: mean-app-webpage